version: "3.9"

services:
  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - nginx-radius
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  web:
    container_name: web
    image: tutum/hello-world:latest
    ports:
      - 8888:80
    networks:
      - nginx-radius

networks:
  nginx-radius:
    external: true
