version: '3'
services:
  web:
    image: tutum/hello-world:latest
    ports:
      - 8000:80

  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - web

volumes:
  htpasswd:
