version: '3'

services:
  my-radius:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-radius-image
    container_name: my-radius
    ports:
      - "1812-1813:1812-1813/udp"
    command: -X
    restart: unless-stopped
