version: "3"
services:
  web:
    image: tutum/hello-world:latest
    ports:
      - 8000:80

  proxy:
    build: .
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - web

  radius:
    image: freeradius/freeradius-server
    volumes:
      - ./radius:/etc/raddb
    ports:
      - 1812:1812/udp
      - 1813:1813/udp

volumes:
  nginx.htpasswd:
  radius:
