version: "3.9"

services:
  auth-backend:
    container_name: auth-backend
    build:
      context: .
      dockerfile: Dockerfile.auth-backend
    ports:
      - "8000:8000"
    environment:
      RADIUS_SECRET: testing123
      RADIUS_SERVER: my-radius
    networks:
      - nginx-radius

networks:
  nginx-radius:
    external: true
